title: Jason Zhang
description: Portfolio website
theme: minimal
markdown: kramdown
highlighter: rouge
permalink: pretty

# Optional social links for the footer (you can add or remove as needed)
social_links:
  - title: GitHub
    url: https://github.com/yourusername
  - title: LinkedIn
    url: https://linkedin.com/in/yourprofile
  - title: Twitter
    url: https://twitter.com/yourhandle
