title: Jason Zhang
description: Portfolio website
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
highlighter: rouge
permalink: pretty

# Optional social links for the footer (you can add or remove as needed)
social_links:
  - title: GitHub
    url: https://github.com/yourusername
  - title: LinkedIn
    url: https://linkedin.com/in/yourprofile
  - title: Twitter
    url: https://twitter.com/yourhandle
