title: "Jason Zhang | Data Science, Engineering, and Software Development Portfolio"
description: "A portfolio showcasing my work in data science, engineering, and software development."
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme  # Ensure this is included to use the remote theme
markdown: kramdown
highlighter: rouge
permalink: pretty

# Optional social links for the footer (customized with your actual URLs)
social_links:
  - title: "GitHub"
    url: https://github.com/jjz17
  - title: "LinkedIn"
    url: https://linkedin.com/in/jjz17

# Optional footer links
footer_links:
  - title: "Live Portfolio"
    url: https://jjz17.github.io

# Additional settings
paginate: 5
